name: Ruff Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ruff.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ruff.yml'

jobs:
  lint:
    name: Ruff Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff>=0.8.0

    - name: Run Ruff linter
      run: |
        ruff check power_monitor/ generate_icons.py --output-format=github

    - name: Run Ruff formatter check
      run: |
        ruff format --check power_monitor/ generate_icons.py
